- name: bug
  color: d73a4a
  description: Something isn't working
- name: enhancement
  color: a2eeef
  description: New feature or request
- name: security
  color: 8f0b0b
  description: Security-related
- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation
- name: good first issue
  color: 7057ff
  description: Good for newcomers
