name: ci-matrix
true:
  push:
    branches:
    - main
  pull_request: null
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-test:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        build_type:
        - Debug
        - Release
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    steps:
    - uses: step-security/harden-runner@v2
      with:
        egress-policy: audit
    - uses: actions/checkout@v4
    - name: ccache cache
      uses: actions/cache@v4
      with:
        path: '~/.cache/ccache

          '
        key: ccache-${{ runner.os }}-${{ hashFiles('**/*.cpp','**/*.cc','**/*.c','**/*.hpp','CMakeLists.txt')
          }}
        restore-keys: 'ccache-${{ runner.os }}-

          '
    - name: Install ccache
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y ccache
    - name: Configure
      run: cmake -S . -B build -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} -D QUASAR_ENABLE_TESTS=ON
        -D CMAKE_CXX_COMPILER_LAUNCHER=ccache
    - name: Build
      run: cmake --build build -j
    - name: Test
      run: ctest --test-dir build --output-on-failure
'on':
- workflow_dispatch
