name: sync-labels
true:
  push:
    branches:
    - main
  workflow_dispatch: null
jobs:
  labels:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: crazy-max/ghaction-github-labeler@v5
      with:
        yaml-file: .github/labels.yml
        skip-delete: true
'on':
- workflow_dispatch
