name: macos-arm64
true:
- push
- pull_request
jobs:
  build:
    continue-on-error: true
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -D QUASAR_ENABLE_TESTS=ON
    - name: Build
      run: cmake --build build -j
    - name: Test
      run: ctest --test-dir build --output-on-failure
'on':
- workflow_dispatch
