name: Secret Scan
true:
  push: {}
  pull_request: {}
jobs:
  gitleaks:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gitleaks/gitleaks-action@v2
      with:
        args: detect --no-git -v
'on':
- workflow_dispatch
